public class SYS_Constants {
	public static Integer TEXT_AREA_MAX_SIZE {
        get {
            return 131072;
        }
    }
    public static Integer MAX_DATA_FIELDS {
        get{
            return 10;  
        }
    }
    public static FINAL String OUTBOUND = 'OUTBOUND';
    public static FINAL String INBOUND = 'OUTBOUND';
    public static FINAL String SYSMERGE = 'MERGE';
    public static string JIRA_PROJECT = System.Label.JIRA_projectName; 
    public static string project_key = 'issue.fields.project.key';
    public static String INT_TYPE = 'JIRA'; //Quickbooks  Middleware_hl7 IMS_SIU JIRA
    public static String PRICEBOOK = 'Standard'; // Standard , Standard Price Book
    
}